
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module OSCILL(

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,
	
	///////// DRAM /////////
      output      [12:0] DRAM_ADDR,
      output      [1:0]  DRAM_BA,
      output             DRAM_CAS_N,
      output             DRAM_CKE,
      output             DRAM_CLK,
      output             DRAM_CS_N,
      inout       [15:0] DRAM_DQ,
      output             DRAM_LDQM,
      output             DRAM_RAS_N,
      output             DRAM_UDQM,
      output             DRAM_WE_N,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	//output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



oscill_nios nios
(

		/////////AUDIO////////////
		
		.audio_ADCDAT(AUD_ADCDAT),
		.audio_ADCLRCK(AUD_ADCLRCK),
		.audio_BCLK(AUD_BCLK),
		.audio_DACDAT(AUD_DACDAT),
		.audio_DACLRCK(AUD_DACLRCK),
		
		.audio_config_SDAT(FPGA_I2C_SDAT),
		.audio_config_SCLK(FPGA_I2C_SCLK),
		
		.audio_clk_clk(AUD_XCK),
		
		////////CLK//////////////

		.clk_clk(CLOCK_50),
		
		///////RESET/////////////
		
		.reset_reset_n(KEY[0]),
		
		////////HEX/////////////
		
		.pio_hex_0_external_connection_export(HEX0),
		.pio_hex_1_external_connection_export(HEX1),
		.pio_hex_2_external_connection_export(HEX2),
		.pio_hex_3_external_connection_export(HEX3),
		.pio_hex_4_external_connection_export(HEX4),
		.pio_hex_5_external_connection_export(HEX5),
		
		///////KEY//////////////
		
		.pio_key_external_connection_export(KEY[3:1]),
		
		///////LED//////////////
		
		//.pio_led_external_connection_export(LEDR),
		
		///////SWITCH////////////
		
		.pio_sw_external_connection_export(SW),
		
		///////VGA///////////////
		
		.vga_CLK(VGA_CLK),
		.vga_HS(VGA_HS),
		.vga_VS(VGA_VS),
		.vga_BLANK(VGA_BLANK_N),
		.vga_SYNC(VGA_SYNC_N),
		.vga_R(VGA_R),
		.vga_G(VGA_G),
		.vga_B(VGA_B)
);

endmodule
